### PR TITLE
Some litter optimization including capitalization problems

### PR DESCRIPTION
**Pull request by ThreeManager785**
By the way, I added a hidden toggle which can only be changed via editing code since I think it's inharmony to insert an icon in symbols. Delete if you mind, this toggle cannot be toggled in App in anyway.

### CODE REVIEW

**Comment by WindowsMEMZ** [comment]
!Run check

**Review by WindowsMEMZ — APPROVED** [review]

**Comment by WindowsMEMZ** [comment]
有合并冲突需要解决

**Comment by Groupguanfang** [comment]
👀怎么看到了原神😂

**Comment by WindowsMEMZ** [comment]
These localizations were outdated, closing this pull request.

**Pull request closed without merging**
